import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Wine, Star, ShoppingCart } from 'lucide-react';
const PersonalizedRecommendations = () => {
    const recommendations = [
        { id: 1, name: 'Chateau Margaux 2016', type: 'Red', region: 'Bordeaux', rating: 98, price: 899.99, description: 'A perfect blend of power and finesse. Recommended based on your love for full-bodied reds.' },
        { id: 2, name: 'Krug Grande Cuvée', type: 'Champagne', region: 'Champagne', rating: 96, price: 249.99, description: 'Luxurious and complex. Suggested due to your preference for premium sparkling wines.' },
        { id: 3, name: 'Sassicaia 2018', type: 'Red', region: 'Tuscany', rating: 97, price: 349.99, description: 'Bold and elegant Super Tuscan. Recommended based on your ratings of Italian wines.' },
        { id: 4, name: 'Cloudy Bay Sauvignon Blanc 2022', type: 'White', region: 'Marlborough', rating: 93, price: 34.99, description: 'Crisp and aromatic. Suggested to diversify your white wine experience.' },
    ];
    return (_jsxs("div", { className: "p-6", children: [_jsx("h1", { className: "text-3xl font-semibold mb-6", children: "Personalized Wine Recommendations" }), _jsx("p", { className: "text-gray-400 mb-6", children: "Based on your taste profile, purchase history, and ratings, we think you'll love these wines:" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: recommendations.map((wine) => (_jsxs("div", { className: "bg-gray-800 rounded-lg shadow-md p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Wine, { className: "h-8 w-8 text-red-500 mr-3" }), _jsx("h2", { className: "text-xl font-semibold", children: wine.name })] }), _jsxs("div", { className: "flex items-center", children: [_jsx(Star, { className: "h-5 w-5 text-yellow-500 mr-1" }), _jsx("span", { className: "font-bold", children: wine.rating })] })] }), _jsxs("p", { className: "text-gray-400 mb-2", children: [wine.type, " | ", wine.region] }), _jsx("p", { className: "mb-4", children: wine.description }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("span", { className: "text-2xl font-bold", children: ["$", wine.price.toFixed(2)] }), _jsxs("button", { className: "bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 transition-colors duration-200 flex items-center", children: [_jsx(ShoppingCart, { className: "h-5 w-5 mr-2" }), "Add to Cart"] })] })] }, wine.id))) })] }));
};
export default PersonalizedRecommendations;
