import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Wine, ChevronDown } from 'lucide-react';
import { useTheme } from '../contexts/ThemeContext';
const AuthHeader = () => {
    const { theme } = useTheme();
    const isDark = theme === 'dark';
    return (_jsx("header", { className: `fixed top-0 w-full ${isDark ? 'bg-black/90' : 'bg-white/90'} backdrop-blur-sm z-50 border-b ${isDark ? 'border-gray-800' : 'border-gray-200'}`, children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6", children: _jsx("div", { className: "flex justify-between items-center py-4", children: _jsxs("div", { className: "flex items-center", children: [_jsxs(Link, { to: "/", className: "flex items-center", children: [_jsx(Wine, { className: "h-8 w-8 text-green-500 mr-2" }), _jsx("span", { className: `text-xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`, children: "Cuvee Club" })] }), _jsxs("nav", { className: "hidden md:flex items-center ml-10 space-x-8", children: [_jsxs("div", { className: "relative group", children: [_jsxs("button", { className: `flex items-center ${isDark ? 'text-gray-300 hover:text-white' : 'text-gray-600 hover:text-gray-900'}`, children: ["Product", _jsx(ChevronDown, { className: "ml-1 h-4 w-4" })] }), _jsx("div", { className: "absolute left-0 mt-2 w-48 rounded-md shadow-lg bg-white dark:bg-gray-900 ring-1 ring-black ring-opacity-5 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200", children: _jsxs("div", { className: "py-1", children: [_jsx(Link, { to: "/features", className: `block px-4 py-2 text-sm ${isDark ? 'text-gray-300 hover:bg-gray-800' : 'text-gray-700 hover:bg-gray-100'}`, children: "Features" }), _jsx(Link, { to: "/integrations", className: `block px-4 py-2 text-sm ${isDark ? 'text-gray-300 hover:bg-gray-800' : 'text-gray-700 hover:bg-gray-100'}`, children: "Integrations" })] }) })] }), _jsx(Link, { to: "/pricing", className: `${isDark ? 'text-gray-300 hover:text-white' : 'text-gray-600 hover:text-gray-900'}`, children: "Pricing" })] })] }) }) }) }));
};
export default AuthHeader;
